Vagrant.configure("2") do | config |
  config.vm.box = "roboxes/fedora35"
  #config.disksize.size = '20GB'
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "fedora35"
    vbox.memory = 2048
    vbox.cpus = 2
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    yes | sudo dnf upgrade
  SHELL
#  config.vm.provision "Basic setup", type: "shell",
#    path: "vagrant/inital_setup.sh", privileged: true
  config.vm.synced_folder "./vagrant", "/vagrant",
    owner: "vagrant", group: "vagrant", create: true
end
